version: '3.3'
services:
  home-assistant:
    container_name: homeassistant
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Asia/Calcutta
    volumes:
      - '/haConfig:/config'
    network_mode: host
    image: 'ghcr.io/home-assistant/home-assistant:stable'