//
// Created by Tamse, Mahesh on 16/04/23.
//

#ifndef CUSTOMCLOCKNEW_CONSTANTS_H
#define CUSTOMCLOCKNEW_CONSTANTS_H

#define GLOBAL_MAX_LOOP_TIMEOUT 90
#define DEBUG_ENABLED 0

// ----------- NTP Constants ----------- //
#define NTP_POLL_INTERVAL 5
#define BASE_NTP_OFFSET (3600 * 5 + 1800)


// ----------- MQTT Constants ----------- //
#define MQTT_SERVER_HOST "43d985e2b31746e6980bc97ba5b1d77d.s1.eu.hivemq.cloud"
#define MQTT_SERVER_PORT 8883
#define MQTT_SERVER_USER "nodeUser"
#define MQTT_SERVER_PASSWORD "nodePasswd"
#define MQTT_SERVER_CONNECT_RETRY 10
#define MQTT_SERVER_QOS 1

#if defined(ESP32)
static const char *root_ca = R"EOF(
-----BEGIN CERTIFICATE-----
MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
-----END CERTIFICATE-----
)EOF";
#endif


#define MQTT_SUBSCRIPTION "cmd/#"
#define LED_CONTROL_MQTT_CMD "cmd/led/"
#define LED_CONTROL_MQTT_STAT "status/led/"
#define COLOR_MODE_CONTROL_MQTT_CMD "cmd/colorMode/"
#define CUSTOM_MSG_CONTROL_MQTT_CMD "cmd/customMsg/"
#define HEAP_UTILIZATION_DATA_MQTT_TOPIC "status/heap/available"

// ----------- LED Constants ----------- //
#define LED_PER_DIGIT_SEGMENT 7
#define SEGMENTS_PER_DIGIT 7
#define LED_PER_DOT_SEGMENT 4
#define POSITION_DOT_SEGMENT 2
#define SEGMENTS_PER_DOT 2
#define DOT_BLINK_INTERVAL 1
#define LED_TOTAL (LED_PER_DIGIT_SEGMENT*SEGMENTS_PER_DIGIT* 4 + SEGMENTS_PER_DOT*LED_PER_DOT_SEGMENT)


// ----------- LedWrapper Constants -------//
#define CLOCK_UPDATE_PARAM_RGB "color"
#define CLOCK_UPDATE_PARAM_RGB_R "r"
#define CLOCK_UPDATE_PARAM_RGB_G "g"
#define CLOCK_UPDATE_PARAM_RGB_B "b"
#define CLOCK_UPDATE_PARAM_COLOR_MODE "color_pattern"
#define CLOCK_UPDATE_PARAM_COLOR_PATTERN_INDEX "color_pattern_index"

//this param is for MQTT lights on HA... This has to be constant set below
#define CLOCK_UPDATE_PARAM_HA_COLOR_MODE "color_mode"
#define CLOCK_UPDATE_VAL_HA_COLOR_MODE "rgb"

#define CLOCK_UPDATE_PARAM_BRIGHTNESS "brightness"
#define CLOCK_UPDATE_PARAM_FILLER_DIGIT "filler_digit"
#define CLOCK_UPDATE_PARAM_STATE_KEY "state"
#define CLOCK_UPDATE_PARAM_STATE_ON "ON"
#define CLOCK_UPDATE_PARAM_STATE_OFF "OFF"



// ----------- ColorManager Constants -------//
#define COLOR_MANAGER_MODES_LEN 3

#define COLOR_MANAGER_MODE_RGB 0
#define COLOR_MANAGER_MODE_PALETTE 1
#define COLOR_MANAGER_MODE_PALETTE_SHUFFLE 2

#define COLOR_MANAGER_MODE_DEFAULT 1

// ----------- Storage Constants ----------- //
#define STORAGE_FILE_NAME "/data.json"
#define WAIT_FOR_CYCLES_FOR_COMMIT 100

#define PARAM_DEVICE_ID "Device_ID"
#define PARAM_API_KEY "API_Key"
#define PARAM_AM_PM "AM_PM"
#define PARAM_RGB_VAL "RGB_VALUE"
#define PARAM_BRIGHTNESS_VAL "BRIGHTNESS"
#define PARAM_MIN_OFFSET_VAL "MIN_OFFSET"


#define HEAP_STATUS_INTERVAL 30
#define HEAP_DEVIATION_PERCENT 10


#endif //CUSTOMCLOCKNEW_CONSTANTS_H
